import requests
import os
from dotenv import load_dotenv

load_dotenv()

def build_prompt(anomaly_summary: list[dict]) -> str:
    lines = []
    for a in anomaly_summary:
        lines.append(
            f"- {a['label']} detected on host '{a['host']}'\n"
            f"  Metric: {a['metric']}, Peak value: {a['peak_value']}, "
            f"Z-score: {a['peak_z']}, Time: {a['peak_time']}, "
            f"Flagged data points: {a['count']}"
        )
    anomaly_text = "\n".join(lines)

    prompt = f"""You are an expert Site Reliability Engineer (SRE).
The following anomalies have been detected in production system metrics:

{anomaly_text}

Generate a structured incident runbook with these exact sections:

## Incident Summary
A 2-3 sentence plain-English summary of what is happening.

## Root Cause Analysis
The most likely causes based on the metrics provided.

## Immediate Actions
A numbered list of steps the on-call engineer should take RIGHT NOW.

## Investigation Commands
3-5 specific Splunk SPL queries the engineer should run to investigate further.

## Escalation Criteria
When should this be escalated, and to whom?

Keep the tone calm, technical, and actionable. Be specific."""
    return prompt


def generate_runbook(anomaly_summary: list[dict]) -> str:
    if not anomaly_summary:
        return "✅ No anomalies detected. System operating normally."

    prompt = build_prompt(anomaly_summary)

    try:
        response = requests.post(
            "http://localhost:11434/api/generate",
            json={
                "model": "llama3.2",
                "prompt": prompt,
                "stream": False
            },
            timeout=120
        )
        if response.status_code == 200:
            result = response.json()
            runbook_text = result.get("response", "")
            if runbook_text:
                print("✅ AI runbook generated via Ollama (llama3.2)")
                return runbook_text
        print(f"⚠️ Ollama returned {response.status_code} — using template")
        return _template_runbook(anomaly_summary)

    except Exception as e:
        print(f"⚠️ LLM call failed: {e} — using template runbook")
        return _template_runbook(anomaly_summary)


def _template_runbook(anomaly_summary: list[dict]) -> str:
    lines = ["# 🚨 Incident Runbook — Auto-generated by Ops Autopilot\n"]
    lines.append("## Incident Summary")
    for a in anomaly_summary:
        lines.append(
            f"- **{a['label']}** on `{a['host']}`: "
            f"{a['metric']} peaked at {a['peak_value']} "
            f"(z-score: {a['peak_z']}) at {a['peak_time']}"
        )
    lines.append("\n## Immediate Actions")
    lines.append("1. Check system resource usage on the affected host immediately")
    lines.append("2. Review recent deployments or configuration changes")
    lines.append("3. Check for upstream dependency failures")
    lines.append("4. Alert the on-call team if metrics do not recover within 5 minutes")
    lines.append("\n## Investigation Queries (run in Splunk)")
    for a in anomaly_summary:
        lines.append(
            f"```\nindex=ops_metrics host={a['host']} "
            f"| timechart span=1m avg({a['metric']})\n```"
        )
    lines.append("\n## Escalation")
    lines.append("Escalate to senior SRE if anomaly persists beyond 15 minutes.")
    return "\n".join(lines)


if __name__ == "__main__":
    test_summary = [
        {"label": "CPU spike", "metric": "cpu_pct", "peak_value": 92.3,
         "peak_z": 4.7, "peak_time": "2026-06-07 10:05:00",
         "host": "prod-server-01", "count": 15},
        {"label": "Memory leak", "metric": "memory_pct", "peak_value": 89.1,
         "peak_z": 3.9, "peak_time": "2026-06-07 01:12:00",
         "host": "prod-server-01", "count": 30},
    ]
    runbook = generate_runbook(test_summary)
    print(runbook)